// Auto-generated file - do not edit manually
// Generated at: 2025-11-30T07:57:31.400Z

// Hierarchical permissions (includes parent route permissions)
export const routePermissions: Record<string, string[]> = {
  '/': [],
  '/pricing': [],
  '/charts': [],
  '/order': [],
  '/backoffice': ['client:read'],
  '/[clientId]': ['cv:read'],
  '/backoffice/clients': ['client:read'],
  '/auth/reset-password': [],
  '/auth/register': [],
  '/auth/login': [],
  '/auth/forgot-password': [],
  '/[clientId]/dashboard': ['cv:read'],
  '/[clientId]/cv': ['cv:read'],
  '/[clientId]/analyze': ['cv:read'],
  '/backoffice/clients/create': ['client:read'],
  '/backoffice/clients/[clientId]': ['client:read'],
  '/[clientId]/cv/[cvId]': ['cv:read'],
  '/[clientId]/analyze/[id]': ['cv:read'],
  '/[clientId]/cv/[cvId]/update': ['cv:read', 'cv:update'],
  '/api/backoffice/clients': [],
  '/api/auth/reset-password': [],
  '/api/auth/forgot-password': [],
  '/api/auth/[...nextauth]': [],
  '/api/[clientId]/cv': [],
  '/api/backoffice/clients/[clientId]': [],
  '/api/[clientId]/cv/[id]': [],
  '/api/[clientId]/cv/analyze': [],
  '/:clientId': ['cv:read'],
  '/auth': [],
  '/:clientId/dashboard': ['cv:read'],
  '/:clientId/cv': ['cv:read'],
  '/:clientId/analyze': ['cv:read'],
  '/backoffice/clients/:clientId': ['client:read'],
  '/:clientId/cv/:cvId': ['cv:read'],
  '/:clientId/analyze/:id': ['cv:read'],
  '/:clientId/cv/:cvId/update': ['cv:read', 'cv:update'],
  '/api': [],
  '/api/backoffice': [],
  '/api/auth': [],
  '/api/auth/*': [],
  '/api/[clientId]': [],
  '/api/:clientId/cv': [],
  '/api/backoffice/clients/:clientId': [],
  '/api/:clientId/cv/:id': [],
  '/api/:clientId/cv/analyze': [],
} as const;
